### ISSUE TITLE
请教个问题，自定义token名称（打扰了）

### ISSUE THREAD

**Issue by lulei0215** [abitmore/bts-cn-docs#10]
bts跑起来没有问题，现在能修改bts变为自定义的token名吗 就是起个别的名字的币。
google了 修改的三个文件，可能是版本早了 ，找不到对应BTS在哪里文件

**Comment by abitmore** [comment]
你对比一下相同版本号的 testnet 分支 和 master 分支就应该知道要改哪些内容了。
