### ISSUE TITLE
需要协助

### ISSUE THREAD

**Issue by algerpan** [abitmore/bts-cn-docs#4]
你好，

我通过bitshares团队的Dr. Fabian Schuh的介绍找到这个目录，目前我们团队正在做bts的调研，碰上许多技术细节，请问是否可以添加一个即时通讯工具例如telegram、slack或者微信向您请教问题？ 
slack: algerpan@outlook.com
telegram: Alger Pan
wechat: pankaiyang001

谢谢

**Comment by abitmore** [comment]
Telegram提供的不是带 @ 的 Username 我不知道怎么搜。
微信号搜不到。

**Comment by algerpan** [comment]
你好，

请再尝试一次微信号搜索，现在应该可以搜索到了，抱歉之前做了搜索设置。

谢谢
