### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by sman2013** [abitmore/bts-cn-docs#6]
参考文档：https://github.com/abitmore/bts-cn-docs/blob/master/%E4%BD%BF%E7%94%A8VisualStudio2015%E7%BC%96%E8%AF%91BitShares-Core.txt

环境：win10+vs community 2015 update1
通过cmake-gui生成VS工程
编译时发现缺少curl
在github上下载的curl-7.59.0，编译生成
提取目录[libcurl-vc14-x64-release-static-ipv6-sspi-winssl]下的 libcurl_a.lib 及相应的头文件
在VS上添加头文件目录及链接库目录
发现链接库中输入curl名为：curl.lib（自己强制修改为libcurl_a.lib）
再次编译 发生：
1>------ 已启动生成: 项目: build_hardfork_hpp, 配置: Release x64 ------
1>  File "F:/bitshares/vcproject/libraries/chain/include/graphene/chain/hardfork.hpp" up-to-date with .d directory
2>------ 已启动生成: 项目: graphene_egenesis_full, 配置: Release x64 ------
2>  Building Custom Rule F:/bitshares/bitshares-core/libraries/egenesis/CMakeLists.txt
2>  CMake does not need to re-run because F:/bitshares/vcproject/libraries/egenesis/CMakeFiles/generate.stamp is up-to-date.
2>  Generating egenesis_brief.cpp, egenesis_full.cpp
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 -1073741515。
========== 生成: 成功 1 个，失败 1 个，最新 14 个，跳过 0 个 ==========

请问哪位遇到过同样问题 怎么解决的

**Comment by abitmore** [comment]
CURL 的问题我还没来得及写到文档。

另外那个问题，试试自己编 openssl 。

**Comment by abitmore** [comment]
我碰到过这个问题或者类似的，当时是自己编 openssl 解决的。

**Comment by abitmore** [comment]
看你在那边贴的日志，好像是 Debug 模式编译的？不知道有没有关系，我没有试过 Debug ，一直是用 Release 的。

**Comment by abitmore** [comment]
也可以试下 debug 那个 embed_genesis 程序。
